### ISSUE TITLE
Add course-file wide hooks

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/reckoner#130]
There are certain things that might need to be done before _any_ helm charts are installed which might. be necessary for more than one chart.  Right now the use-case is for a priority class to be created that will be used by several charts.

I propose that we add a `pre_plot` and `post_plot` hook, similar to the chart hooks, that exists at the top level course.yml.  This should not run during --dry-run, and should potentially cause the entire course to fail immediately if it fails.

**Comment by endzyme** [comment]
:thinking: This is an interesting feature request. There are problems today with how we run hooks, especially since some of them are run every time. These types of setup jobs seem to be a little different than hooks that are potentially not idempotent. I know right now we have some hooks that have a "idempotency workaround" like `kubectl get ns my-namespace >/dev/null 2>&1 || kubectl create ns my-namespace`. 

These hooks feel like there are two use cases, one being "always run this every time" and some that are "only run once."

Something to think about for maybe a future feature or some accommodation for non-idempotent commands.

Apart from that thought, I think the request here seems reasonable and we should see if we can add it to our next planning cycle.
