### ISSUE TITLE
Change helm version regex to make the +SHA string optional

### ISSUE THREAD

**Issue by ludovicc** [FairwindsOps/reckoner#436]
Hello,

I'm trying to use Reckoner but it seems that it cannot recognize the version of Helm on my machine.

I used Nix packages (https://nixos.org) to install Helm, and maybe the version returned by Helm from this package manager cannot be recognised by Reckoner.

```
> helm version --short
v3.3.1

> reckoner template envs/staging.yaml --run-all
ERROR Could not find version!! Could the helm response format have changed?
                STDOUT: v3.3.1

                STDERR:
                COMMAND: helm version --short
⛵🔥 Encountered errors while reading course file ⛵🔥
Helm Client Failed to initialize: Could not detect helm version
```

Thank you!

**Comment by sudermanjr** [comment]
What version of reckoner?

**Comment by ludovicc** [comment]
It's a fresh version from pipy: reckoner, version 4.3.2

**Comment by sudermanjr** [comment]
Interesting. It seems like the version nix is distributing is not the same in some ways as the upstream.

We use [this regex](https://github.com/FairwindsOps/reckoner/blob/662c91d8e3b2a76222332e4471920717fc560b65/reckoner/helm/client.py#L239) to parse the version, because the client that Helm distributes has the following output:

```
▶ helm version --short
v3.3.1+g249e521
```
