### ISSUE TITLE
Gitops yaml split into separate files

### ISSUE THREAD

**Issue by lucasreed** [FairwindsOps/reckoner#572]
Per the [design doc](https://github.com/FairwindsOps/reckoner/files/8484122/Reckoner_Gitops_Functionality_Design_Doc.pdf), we need to ensure that yaml output from the `reckoner template --gitops` command will be split up into individual yaml files. The doc can be referenced for thoughts on the default directory layout as well.

**Comment by intrand** [comment]
I'd like to see this support a kustomize "base" per release so further customization that the helm chart doesn't support can be done easily. I don't think this feature should handle setting up any overlay(s) or any kustomzation.yaml files outside of the base, since users may have different layouts, custom files added, etc.
