### ISSUE TITLE
Truthy/Falsey values don't do what you want them to 

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#7]
Carried over from: https://github.com/reactiveops/autohelm/issues/7

**Comment by endzyme** [comment]
I have a suggested method of proceeding forward with a change. Perhaps instead of converting all the values in the course.yml into `--set xyz` params, we could run them as files (native yaml) to the helm command. This would avoid the fidelity loss of type when converting from yaml to `--set`

**Comment by ejether** [comment]
I think that may be a good way to go and would likely not require any change in the `course.yml`

**Comment by stealthybox** [comment]
> instead of converting all the values in the course.yml into --set xyz params, we could run them as files (native yaml)

I think this is the way the feature should have originally been built, but it is a breaking change.
Some of our existing course.yaml's would be affected by this change.

I would recommend either:
- using `values:` as a file
- move the old behavior to `set:`

or
- keeping the `values:` behavior the same
- using `values-file:` as a file

`values-file:` should be of greatest precedence when used with `files:`

**Comment by endzyme** [comment]
Awesome call out. Thanks Leigh! We will likely have to stagger the feature to give time for depreciation of `values:` behavior.

Do you think logging warnings on certain types in `values:` at the end of the run would be a good starting point? We could also add `set:` in the same release with a note that the change is coming. Then we could work on changing the behavior of `values:`.

**Comment by stealthybox** [comment]
@endzyme IMO,
Using `values-file:` for the new behavior is the simplest solution since it's a new key.
Then you can just move `values:` -> `set:` and alias `values:` with a deprecation notice.

A future version could move the alias target from `set:` to `values-file:`.

Detecting keys that would only work with `--set` would be useful.
Basically anything with an unescaped period will change in behavior.

There's probably a few ways you could create a smooth migration path.

**Comment by endzyme** [comment]
@stealthybox - I've decided to bite the bullet and attempt to see what it might look like to warn people about the `values: {}` behavior change and support `sets: {}` functionality.

The current PR implementation merges the `values: {}` and `sets: {}` settings for a chart, and `sets: {}` take precedence (just like the CLI). If someone is using `values: {}` a deprecation notice is displayed as a warning. I also added some debug messages which note that any values will be actually used in `--set` for helm. I am still not sure on the timeframe to fully deprecate the behavior, but at least the fix for today is rename your `values: {}` key to `sets: {}` and you should chug happily along.

**Comment by sudermanjr** [comment]
This may be a bit pedantic or nit-picky, but I think `sets` is a very confusing way to name that.  Maybe something like `set-values` that is slightly more descriptive to the user. I believe there are other concerns as well, but I will wait until I test out this PR.

**Comment by endzyme** [comment]
Thanks @sudermanjr! I don't think that's a nit-pick at all. Valuable feedback and a worthwhile change.

**Comment by stealthybox** [comment]
I suggested `set:` (singular) simply after the flag name.
`set-values:`, `set-flags:`, `set-kv:`, `set-map:` all make sense to me.

**Comment by endzyme** [comment]
Additional information here: All environment variable values do their interpolation by iterating a list of arguments on the command line and interpolating the values in each "arg" string. This will not work and will need a refactor when we support native support values.

**Comment by ejether** [comment]
I'm having a hard time parsing the meaning here: 

> All environment variable values do their interpolation by iterating a list of arguments on the command line and interpolating the values in each "arg" string. This will not work and will need a refactor when we support native support values.

**Comment by endzyme** [comment]
I'm trying to call out that the way we do environment variable interpolation will be affected by the work that needs to happen with this issue. It is extra scope.

**Comment by stealthybox** [comment]
ah, I didn't know reckoner supported env var interpolation -- that's super useful.

We might just consider supporting that for the entire `course.yaml`.

**Comment by endzyme** [comment]
#131 resolved this
